import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AppleStyleDock } from "@/components/ui/demo";
import { getProject, projects } from "@/data/projects";

type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return projects.map(({slug}) => ({slug})); }
export async function generateMetadata({params}: Props): Promise<Metadata> { const {slug}=await params; const project=getProject(slug); if (!project) return {}; return { title: `${project.name} — Aditya Singh`, description: project.summary, alternates: {canonical: `/work/${slug}`}, openGraph: {title: `${project.name} — Aditya Singh`, description: project.summary, url: `/work/${slug}`, images: project.image ? [{url: project.image, alt: project.imageAlt}] : [{url: "/og.png", width: 1200, height: 630}]} }; }
export default async function ProjectPage({params}: Props) { const {slug}=await params; const project=getProject(slug); if(!project) notFound(); return <main id="main-content" className="portfolio-page"><div className="page-shell"><header className="eyebrow-row"><Link href="/work">← ALL WORK</Link><span>CASE STUDY / {project.kind.toUpperCase()}</span></header><article className="case-study"><div className="page-intro"><p className="eyebrow">{project.status} · {project.kind}</p><h1>{project.name}</h1><p>{project.summary}</p><div className="action-row"><a className="button-primary" href={project.source} target="_blank" rel="noopener noreferrer">View source ↗</a>{project.demo && <a className="button-secondary" href={project.demo} target="_blank" rel="noopener noreferrer">Open live prototype ↗</a>}</div></div><div className="case-facts"><div><span>MY ROLE</span><p>{project.role}</p></div><div><span>STATUS</span><p>{project.status}</p></div><div><span>STACK</span><p>{project.stack.join(" · ")}</p></div></div>{project.image && <figure className="case-image"><Image src={project.image} alt={project.imageAlt || ""} width={1440} height={850} sizes="(max-width: 800px) 100vw, 800px" /><figcaption>{project.slug === "pebblecode" ? "Captured from the public PebbleCode prototype." : "Interface screenshot from the public project repository."}</figcaption></figure>}<section className="case-section"><span className="section-index">01 / PROBLEM</span><div><h2>What needed to work</h2><p>{project.problem}</p></div></section><section className="case-section"><span className="section-index">02 / APPROACH</span><div><h2>How I approached it</h2>{project.approach.map(p => <p key={p}>{p}</p>)}</div></section><section className="case-section"><span className="section-index">03 / DECISION</span><div><h2>A meaningful tradeoff</h2><p>{project.decision}</p></div></section><section className="case-section"><span className="section-index">04 / LEARNING</span><div><h2>What this demonstrates</h2><p>{project.lesson}</p><h3>What I would do next</h3><p>{project.next}</p></div></section><div className="case-end"><Link className="text-link" href="/work">← Browse all work</Link><a className="text-link" href="mailto:adityasingh0929@gmail.com">Discuss this project ↗</a></div></article></div><AppleStyleDock /></main>; }
